### ISSUE TITLE
[Chore] Project should successfully build on the first build

### ISSUE THREAD

**Issue by blyscuit** [lngyeen/MySurveyChallenge#25]
## Issue

When downloading the project (can test by checkout the project in a new folder), the first run of the project fails because of missing files.

## Acceptance Criteria

- A new developer can download the project and follow README instruction to build the application on their first attempt.

<img width="255" alt="Screenshot 2567-04-19 at 14 13 55" src="https://github.com/lngyeen/MySurveyChallenge/assets/6356137/d22a9ffe-8486-4025-affe-8f03bb6b06a3">

**Comment by lngyeen** [comment]
@blyscuit I already implement in this PR ;)
https://github.com/lngyeen/MySurveyChallenge/pull/39
