### ISSUE TITLE
[Chore] Add instruction for a new developer

### ISSUE THREAD

**Issue by blyscuit** [lngyeen/MySurveyChallenge#26]
## Issue

There is no instruction on building the project.

## Acceptance Criteria

- Include a step to step documentation for a new develop to build and run the project.

**Comment by lngyeen** [comment]
@blyscuit I already implement in this PR ;)
https://github.com/lngyeen/MySurveyChallenge/pull/39

**Comment by blyscuit** [comment]
@ingyeen Do you not use the `Gemfile` in set up?

**Comment by lngyeen** [comment]
@blyscuit sorry i forgot it :)
https://github.com/lngyeen/MySurveyChallenge/pull/44
