### ISSUE TITLE
[Chore] Running unit test causes the application to behave unexpectedly

### ISSUE THREAD

**Issue by blyscuit** [lngyeen/MySurveyChallenge#27]
## Issue

When running the unit test then rerun the application, the token features is using a new token and fail API calls. User (in this case, developer) then have to re-login but no message was supplied.

## Acceptance Criteria

- Running unit test should not change the application’s stored data.

**Comment by lngyeen** [comment]
@blyscuit I already fixed in this PR ;)
https://github.com/lngyeen/MySurveyChallenge/pull/41
