### ISSUE TITLE
[Feature] Send API as JSON

### ISSUE THREAD

**Issue by blyscuit** [lngyeen/MySurveyChallenge#28]
## Issue

Current API request body is not JSON.

## Acceptance Criteria

- Send API request body as JSON.
- If this feature is not possible, explain why, and explain how should we send more restricted data such as none-String type and nested data (objects).

**Comment by lngyeen** [comment]
@blyscuit I already implement in this PR ;)
https://github.com/lngyeen/MySurveyChallenge/pull/42
