### ISSUE TITLE
[Feature] Supporting multiple application environments

### ISSUE THREAD

**Issue by blyscuit** [lngyeen/MySurveyChallenge#29]
## Issue

In a real world development we will use more than 1 environments. Current application supports only Production environment.

## Acceptance Criteria

- Add a new `dev` environment.
    - `dev` environment uses the same `client_id` and `client_secret` as `production` but should be in a new field for easy modification later.
    - `dev` environment should build using a different bundle id than `production`.
- Developer should be able to select the environment easily from the Xcode UI.
- Explain with code snippet or a PR, how would this feature affects secrets management, including on CICD. What additional tools will you use?

**Comment by lngyeen** [comment]
Hello @blyscuit 
I already implement in this PR ;) https://github.com/lngyeen/MySurveyChallenge/pull/43

Basically I will create another xcconfig file, so we will have 2 xcconfig files, one for dev and one for prod, fill in the values corresponding to each environment into these files. Like this picture:
<img width="893" alt="Screenshot 2024-04-22 at 3 22 25 PM" src="https://github.com/lngyeen/MySurveyChallenge/assets/60918798/98a2ef7f-10a9-453a-a088-60b0c1d0c000">

I will go to the project section and create 2 more configurations (Dev-Debug and Dev-Release) and rename the existing configurations to Prod-Debug and Prod-Release for easy distinction.
<img width="1131" alt="Screenshot 2024-04-22 at 3 22 41 PM" src="https://github.com/lngyeen/MySurveyChallenge/assets/60918798/b5ea0095-589e-4fe6-b3fc-2c54afb5a73a">


And then create another scheme for Dev and select the corresponding configuration in the Edit Scheme section. As shown below:
<img width="1127" alt="Screenshot 2024-04-22 at 3 24 40 PM" src="https://github.com/lngyeen/MySurveyChallenge/assets/60918798/701f347f-7ee6-4e70-89bd-b831a5e9a88f">


Regarding app secrets, there are 2 approaches.
1: If we do not use CI/CD tools, we can create xcconfig files as placeholders (containing only keys, not values). Add them to git ignore to avoid having to push thoes values to the remote repository. And we will share secrets only within the team, developer will manually copy these secrets into xcconfig files manually.
2: We can use secret storage services from CI/CD services. When we run the pipeline, you can write a small script to get these secrets and fill them into the corresponding xcconfig files right before building the project.

**Comment by blyscuit** [comment]
The feature works now. Minor note, the new update seems to break fastfile `testLane`.

**Comment by lngyeen** [comment]
> The feature works now. Minor note, the new update seems to break fastfile `testLane`.

I fixed ;) https://github.com/lngyeen/MySurveyChallenge/pull/45
