### ISSUE TITLE
[Question] Localization workflow

### ISSUE THREAD

**Issue by blyscuit** [lngyeen/MySurveyChallenge#30]
## Issue

- How do you manage multiple languages in the application?

- What tools do you use to manage multiple languages?

- Do you manage localization on CICD as well?

**Comment by lngyeen** [comment]
To be honest, I haven't paid attention to this topic in a long time :)

The usual way is to add supported languages to the xcode project and use .strings files to store translated text, and use NSLocalizedString to load them into the UI. This is the way that encouraged by Apple, but with this method, the user must change the language in the iOS Settings app.

Another way is switching locale inside the app code. In the project we are working on, we use the library https://github.com/marmelroy/Localize-Swift. Basically it will change the AppleLanguages stored in UserDefaults and notify a notification named LCLLanguageChangeNotification, based on this notification we will re-render the UI. We also use https://app.phrase.com/ to store translated texts and write a small script to fetch localized texts and generate swift code from localized strings files but in a very simple format. In terms of generating swift code, I think we should switch to https://github.com/SwiftGen/SwiftGen to get more support.

No we did not manage localization on CICD.
