### ISSUE TITLE
[Question] lint

### ISSUE THREAD

**Issue by blyscuit** [lngyeen/MySurveyChallenge#38]
## Issue

What lint means to you in your workflow? What tools do you use to lint?

**Comment by lngyeen** [comment]
@blyscuit 
Yes, I do use linting to ensure source code is cleanly and follows code style rules and best practices. Linting helps detect and fix syntax errors (`swiftlint autocorrect`), or other problems automatically, improving source code quality and minimizing the possibility of errors.
I our project we use SwiftLint: https://github.com/realm/SwiftLint. Just follow the guide to setup and update rules inside `.swiftlint.yml` file to fit with team coding rules and conventions.

**Comment by blyscuit** [comment]
@lngyeen Thank you for the clear answer.
